SPACE_CADET_ENABLE = no
BOOTMAGIC_ENABLE = no
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = no
OLED_ENABLE = yes
WPM_ENABLE = yes

# RGB_MATRIX_SUPPORTED = no
# BACKLIGHT_ENABLE = no
# UNICODE_ENABLE   = no
# BLUETOOTH_ENABLE = no
# CONSOLE_ENABLE = no
# COMMAND_ENABLE = no
# EXTRAFLAGS += -flto
# AUDIO_ENABLE = no
#LEADER_ENABLE = no
# LTO_ENABLE = yes
#MIDI_ENABLE = no